name: rhub (additional CRAN checks - 04)

on:
  workflow_run:
    workflows: [ "Source Code" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
      GITHUB_ACTIONS: "true"
    strategy:
      fail-fast: false
      matrix:
        container:
          - name: nold
            image: ghcr.io/r-hub/containers/nold:latest
          - name: noremap
            image: ghcr.io/r-hub/containers/noremap:latest
          - name: nosuggests
            image: ghcr.io/r-hub/containers/nosuggests:latest
    name: ${{ matrix.container.name }}
    container:
      image: ${{ matrix.container.image }}
    steps:
      - name: Checkout src repo
        uses: actions/checkout@v6
        with:
          ref: 'src'

      - name: Install dependencies
        run: |
          R -q -e 'if (!require("pak")) install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))'
          R -q -e 'pak::pkg_install(c("deps::.", "any::rcmdcheck"), dependencies = TRUE)'

      - name: R-CMD-check
        uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
